import { describe, expect, it } from 'vitest';
import provinceData from '@/data/provinces.json';
import seeds from '@/data/countries.seed.json';
import topology from '../../../public/provinces.json';

/**
 * The province map is generated by scripts/build-provinces.mts and committed.
 * These checks guard the generated data itself, so a rebuild that breaks an
 * invariant fails here rather than in a game.
 */
const provinces = provinceData.provinces;
const byId = new Map(provinces.map((p) => [p.id, p]));
const countryIds = new Set(seeds.map((s) => s.id));

describe('the province map', () => {
  it('has a province record for every shape, and a shape for every record', () => {
    const shapeIds = (topology.objects.provinces.geometries as { id: string }[]).map((g) => g.id);
    expect(new Set(shapeIds).size).toBe(shapeIds.length);
    expect([...shapeIds].sort()).toEqual(provinces.map((p) => p.id).sort());
  });

  it('gives every playable country at least one province, and nothing else any', () => {
    const covered = new Set(provinces.map((p) => p.countryId));
    expect([...countryIds].filter((id) => !covered.has(id))).toEqual([]);
    expect([...covered].filter((id) => !countryIds.has(id))).toEqual([]);
  });

  it('splits big countries into many provinces and keeps small ones whole', () => {
    const count = (countryId: string) => provinces.filter((p) => p.countryId === countryId).length;
    expect(count('643')).toBeGreaterThan(40); // Russia
    expect(count('840')).toBeGreaterThan(40); // United States
    expect(count('276')).toBeGreaterThanOrEqual(6); // Germany
    expect(count('442')).toBe(1); // Luxembourg
    expect(provinces.length).toBeGreaterThan(1200);
    expect(provinces.length).toBeLessThan(2000);
  });

  it('marks exactly one capital per country, where its capital city is', () => {
    for (const id of countryIds) {
      expect(provinces.filter((p) => p.countryId === id && p.capital), id).toHaveLength(1);
    }
    expect(provinces.find((p) => p.countryId === '250' && p.capital)?.city?.name).toBe('Paris');
    expect(provinces.find((p) => p.countryId === '392' && p.capital)?.city?.name).toBe('Tokyo');
  });

  it('shares each country’s population out across its provinces', () => {
    for (const seed of seeds) {
      const own = provinces.filter((p) => p.countryId === seed.id);
      const total = own.reduce((sum, p) => sum + p.population, 0);
      // Each province is rounded to the nearest thousand people.
      expect(Math.abs(total - seed.population), seed.name).toBeLessThanOrEqual(Math.max(seed.population * 0.02, 1000 * own.length));
    }
  });

  it('has symmetric neighbours and no province without one', () => {
    for (const p of provinces) {
      expect(p.neighbours.length, p.name).toBeGreaterThan(0);
      for (const n of p.neighbours) expect(byId.get(n)?.neighbours, `${p.id} -> ${n}`).toContain(p.id);
    }
  });

  it('connects the whole world, so any province can be reached from any other', () => {
    const start = provinces[0]?.id ?? '';
    const seen = new Set([start]);
    const queue = [start];
    for (let head = 0; head < queue.length; head += 1) {
      for (const n of byId.get(queue[head] ?? '')?.neighbours ?? []) {
        if (!seen.has(n)) {
          seen.add(n);
          queue.push(n);
        }
      }
    }
    expect(seen.size).toBe(provinces.length);
  });

  it('finds borders across countries from the shapes, and crossings over water from the sea links', () => {
    const neighbourCountries = (countryId: string) =>
      new Set(
        provinces
          .filter((p) => p.countryId === countryId)
          .flatMap((p) => p.neighbours.map((n) => byId.get(n)?.countryId)),
      );
    expect(neighbourCountries('250')).toContain('276'); // France - Germany by land
    expect(neighbourCountries('840')).toContain('484'); // USA - Mexico by land
    expect(neighbourCountries('826')).toContain('250'); // UK - France across the Channel
    const sea = new Set(provinceData.seaLinks.map(([a, b]) => `${a ?? ''}|${b ?? ''}`));
    for (const [a = '', b = ''] of provinceData.seaLinks) {
      expect(a < b, `${a}|${b} is ordered`).toBe(true);
      expect(byId.get(a)?.neighbours).toContain(b);
    }
    expect(sea.size).toBe(provinceData.seaLinks.length);
  });

  it('gives every province a unique name within its country', () => {
    for (const id of countryIds) {
      const names = provinces.filter((p) => p.countryId === id).map((p) => p.name);
      expect(new Set(names).size, id).toBe(names.length);
    }
  });
});
